version: 2.1

workflows:
  test_deploy:
    jobs:
      - test

jobs:
  test:
    docker:
      - image: cimg/node:17.2.0
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Run tests
          command: npm run test
